### ISSUE TITLE
label mismatch ggsegICBM::icbm_3d

### ISSUE THREAD

**Issue by jottinog** [ggseg/ggsegICBM#1]
Hi,

first of all, thank you for this awesome package! I apologize if this is not the right place to post this issue but here it goes.

I noticed a duplicate of 'lh_acr' and 'rh_acr' in the region column in the 'icbm_3d' atlas.

Elements 24 and 25 are tagged as 'Superior corona radiata' in the label column, but in the region column these are coded as 'rh_acr' and 'lh_acr'.

All the best,
Jonatan

**Comment by WenjunSu** [comment]
Hi,

I'm a big fan of ggseg and thanks for this amazing tool! However, I noticed that there were only 47 regions in ggsegICBM, the fornix is missing (not the Stria terminalis part), is it possible to add this region in the new version of ggsegICMB? 

Best,

Wenjun

**Comment by drmowinckels** [comment]
thanks for the bug report!
